version: "3.9"

services:
  mongo:
    build: ./development
    restart: always
    environment:
      MONGO_INITDB_DATABASE: development_db
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
